M	ERP.Core/Database/Almacen/DB_MTO_Productos.cs
M	ERP.Core/Database/Catalogos/DB_Catalogos.cs
M	ERP.Core/Database/Negocio/DB_MTO_Proveedores.cs
D	ERP.Core/Database/Reporteador/DB_Reportes_Dinamico.cs
M	ERP.Core/ERP.Core.csproj
M	ERP.Core/Entidades/Negocio/Proveedor.cs
M	ERP.Data/ERP.Data.csproj
M	ERP.Data/ERPContext.cs
D	ERP.Data/Mapping/Negocio/ClaseProveedorMap.cs
M	ERP.Data/Repositories/Interfaces/IContableRepository.cs
M	ERP.Data/Repositories/Schemas/Contabilidad/ContableRepository.cs
M	ERP.Data/UnitOfWork.cs
M	ERP.Entities/ERP.Entities.csproj
D	ERP.Entities/Negocio/ClaseProveedor.cs
M	ERP.Web/App_Data/PublishProfiles/ERPMac.pubxml
M	ERP.Web/Autentificados/Almacen/EntradaSalida.aspx.cs
M	ERP.Web/Autentificados/Compras/Controles/EditarOrdenCompra.ascx.cs
M	ERP.Web/Autentificados/Configurador/TipoDocumento.xml
M	ERP.Web/Autentificados/Contabilidad/CuentasPorCobrar/Detalle/Pago.aspx.cs
M	ERP.Web/Autentificados/Contabilidad/CuentasPorCobrar/Documentos/Abonos.aspx.cs
M	ERP.Web/Autentificados/Contabilidad/CuentasPorCobrar/Documentos/NotasCredito.aspx.cs
M	ERP.Web/Autentificados/Contabilidad/CuentasPorCobrar/Documentos/NotasDevolucion.aspx.cs
M	ERP.Web/Autentificados/Contabilidad/CuentasPorCobrar/Documentos/Pagos.aspx.cs
M	ERP.Web/Autentificados/Fabricacion/Controles/MTO_OrdenAcondicionamientoLTE.ascx
M	ERP.Web/Autentificados/Fabricacion/Controles/MTO_OrdenAcondicionamientoLTE.ascx.cs
M	ERP.Web/Autentificados/Fabricacion/OrdenDeProduccion.aspx.cs
D	ERP.Web/Autentificados/Negocio/Controles/SelectCategoria.ascx
D	ERP.Web/Autentificados/Negocio/Controles/SelectCategoria.ascx.cs
M	ERP.Web/Autentificados/Negocio/Proveedor.aspx
M	ERP.Web/Autentificados/Negocio/Proveedor.aspx.cs
D	ERP.Web/Autentificados/Reporteador/Helper/ReporteVentasPorProducto.aspx
D	ERP.Web/Autentificados/Reporteador/Helper/ReporteVentasPorProducto.aspx.cs
M	ERP.Web/Content/AdminLTE/AdminLTE.css
M	ERP.Web/Content/themes/Page/Menu.css
M	ERP.Web/Scripts/UtilsLTE.js
M	ERPMac.sln
A	cambioscontext.cs
A	cambiosuniwork.cs
A	difcontable.cs
